require_relative 'menu_view.rb'
require_relative 'navigation_node.rb'
require_relative 'operation_controller.rb'
require_relative 'input_view.rb'
require_relative 'operation_view.rb'
require_relative 'menu_controller.rb'

require_relative 'builders/menu_node_builder.rb'
require_relative 'builders/input_view_builder.rb'
require_relative 'builders/operation_node_builder.rb'

require_relative 'config/access_menu_operations.rb'
require_relative 'config/access_menu.rb'
require_relative 'config/goal_menu_operations.rb'
require_relative 'config/main_menu_operations.rb'
require_relative 'config/pocket_menu_operations.rb'
require_relative 'config/mattress_menu_operations.rb'
require_relative 'config/main_menu.rb'
require_relative 'config/goal_menu.rb'
require_relative 'config/pocket_menu.rb'
require_relative 'config/mattress_menu.rb'
require_relative 'config/navigation_tree.rb'

require_relative '../connection/connection.rb'

require_relative '../model/user.rb'
require_relative '../model/account.rb'
require_relative '../model/general_account.rb'
require_relative '../model/pocket_account.rb'
require_relative '../model/movement.rb'
require_relative '../model/transfer_movement.rb'
require_relative '../model/transaction_movement.rb'
require_relative '../model/transaction.rb'
require_relative '../model/transfer.rb'
require_relative '../model/coffer.rb'
require_relative '../model/mattress_coffer.rb'
require_relative '../model/goal_coffer.rb'
require_relative '../model/goal.rb'
